User.create(name: "のらねこ", user_attribute: "保護者")
User.create(name: "イチゴミルク", user_attribute: "保護者")
User.create(name: "みー先生", user_attribute: "保育士")
User.create(name: "あい先生", user_attribute: "保育士")
 
Post.create(title: "夕食後に熱が38度になりました", content: "サンプル", scope: "全員", user_id: 1)
Post.create(title: "明日の遠足の持ち物について", content: "サンプル", scope: "全員", user_id: 1)
Post.create(title: "子供のアレルギーについて", content: "サンプル", scope: "保育士のみ", user_id: 2)
Post.create(title: "卒園式の衣装", content: "サンプル", scope: "全員", user_id: 2)
Post.create(title: "子供の寝付きについて", content: "サンプル", scope: "保育士のみ", user_id: 1)